As a user, I can filter keyword by Adwords existence
gutakk/go-google-scraper pull request #62
Opened 2021-01-15 09:29 UTC by gutakk

## What happened
Resolve #59 

## Insight

Describe in detail how to test the changes. Referenced documentation is welcome as well.

## Proof Of Work

Please show us the implementation: screenshots, gifs, etc.

2021-01-29 08:00 UTC, olivierobert requested changes

2021-01-29 08:00 UTC, olivierobert commented on assets/stylesheets/screens/_keyword.scss
> +      zoom: 3;
`zoom` is [a non-standard CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/zoom) so should be avoided.

In terms of UI, I am pretty sure you never saw a checkbox that big in your life 😆 While it's not a UX/UI contest, do try to think of standard patterns. In this case, having the checkbox on a different row than the inputs would be better:

![image](https://user-images.githubusercontent.com/696529/106247024-8e9d4580-6241-11eb-9fb0-a1f35839d00f.png)

2021-01-29 08:00 UTC, olivierobert commented on controllers/keyword.go
> +		"queryString":    fmt.Sprintf("filter[%s]", models.KeywordCondition),
In some cases, DRY is not ideal. This new implementation couples again the controller with the model which is not great in terms of architecture. 

The frontend form input could be different but not it looks like it must be the same; that's not good flexibility. The following could be fine:
```
{
  "queryString":    "filter[text]",
  "modelCondition": models.KeywordCondition,
}
```

So prefer using the constant only for the `modelCondition` key.

On another perspective, the new implementation also lacks explicitness and clarity. Prefer simpler solutions 😌

2021-01-29 08:00 UTC, olivierobert commented on models/keyword_condition.go
> +			switch conditionName {
Don't use case/switch blocks when there are only two cases if/else is best for that

2021-01-29 10:27 UTC, gutakk commented on models/keyword_condition.go
> +			switch conditionName {
Fixed in f4bd4c599937801d324fa45c0a54475b882e1bac

2021-01-29 10:43 UTC, gutakk commented on controllers/keyword.go
> +		"queryString":    fmt.Sprintf("filter[%s]", models.KeywordCondition),
Good catch. Fixed in dedc8c3b8cf24cfdfbb56e1d83a1905437990e2b

2021-01-29 11:45 UTC, gutakk commented on assets/stylesheets/screens/_keyword.scss
> +      zoom: 3;
I agree, I never see checkbox like I did before 😂 Fixed in 70764dd1ef8b2b090a7c4aed0bea42f032daa628

2021-02-01 08:45 UTC, olivierobert commented on assets/stylesheets/screens/_keyword.scss
> +      zoom: 3;
@gutakk Please update the PR description with the updated UI 🙏

2021-02-02 04:08 UTC, gutakk commented on assets/stylesheets/screens/_keyword.scss
> +      zoom: 3;
Updated 😅

2021-02-02 07:19 UTC, olivierobert approved these changes

2021-02-04 02:48 UTC, carryall approved these changes

2021-02-04 04:28 UTC, merged